# -*- coding: utf-8 -*-
"""todo_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaLgyv8d1M0IdstHR7zeTaZzG2JTO4w9
"""

'''
This script will carry out functions related to a to-do list, based on user input.

The user will be able to select an option from 1 - 5 that will add, view, delete, or mark tasks as completed

'''

def view_tasks(todo_list_dict):
    if not todo_list_dict:
        print("No tasks added yet.")
    else:
        for task, status in todo_list_dict.items():
            print(f"{task}: {'Completed' if status else 'Pending'}")

def add_task(todo_list_dict):
    task = input("Please enter a task: ")
    if task:
        todo_list_dict[task] = False
        print("Task added.")
    else:
        print("No task entered.")

def mark_task_completed(todo_list_dict):
    task = input("Enter the task you would like to mark as completed: ")
    if task in todo_list_dict:
        todo_list_dict[task] = True
        print("Task marked as completed.")
    else:
        print("Task not found.")

def delete_task(todo_list_dict):
    task = input("Enter the task you want to delete: ")
    if task in todo_list_dict:
        del todo_list_dict[task]
        print("Task deleted.")
    else:
        print("Task not found.")

def todo_list_options():
    todo_list_dict = {}
    prompt = """
Please choose one of the following:

1. View Tasks
2. Add Task
3. Mark Task as Completed
4. Delete Task
5. Exit
"""

    while True:
        print(prompt)
        try:
            user_choice = int(input("Enter your choice: "))
            if user_choice == 1:
                view_tasks(todo_list_dict)
            elif user_choice == 2:
                add_task(todo_list_dict)
            elif user_choice == 3:
                mark_task_completed(todo_list_dict)
            elif user_choice == 4:
                delete_task(todo_list_dict)
            elif user_choice == 5:
                print("Exiting...")
                break
            else:
                print("Invalid choice. Please enter a number between 1 and 5.")
        except ValueError:
            print("Please enter a valid number.")

if __name__ == "__main__":
    todo_list_options()